schemaVersion: 2.3.0
metadata:
  name: java-sample-app-jboss-1
  namespace: devashish234073-dev
projects:
  - name: java-sample-app-jboss
    git:
      remotes:
        origin: https://github.com/devashish234073/java-sample-app-jboss.git

components:
  - name: universal-developer-image
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-d071837
      memoryLimit: 1Gi
      sourceMapping: /projects
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      endpoints:
        - name: http-8080
          targetPort: 8080
          exposure: public

commands:
  - id: build
    exec:
      command: "mvn clean package"
      component: universal-developer-image
      workdir: /projects/java-sample-app-jboss

  - id: run
    exec:
      command: >
        cp target/*.war /opt/jboss/wildfly/standalone/deployments/ &&
        /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
      component: universal-developer-image
      workdir: /projects/java-sample-app-jboss
      parallel: true

  - id: test
    exec:
      command: "mvn test"
      component: universal-developer-image
      workdir: /projects/java-sample-app-jboss

volumes:
  - name: m2
    size: 512Mi
